itemset_mining_preparation:
  window_size: 110 # must be divisor of dataset size
  ignore_win_smaller_than: 0.5 # percentage of window size
  windowing_method: beta1 # beta1, mean_sigma, energy
  train_size: 350
  warm_up: True
  param_search: False
  validation_size: 800
  custom_threshold: 0.45 # not used if threshold tuning is enabled
  cut_baseline: True
  quantile: 0.65
  utility_function: max
spmf:
  algorithm: NegFIN #from: Apriori, FPGrowth_itemsets,AprioriTID_Bitset,Eclat,dEclat,HMine,FIN,DFIN,NegFIN,PrePost+,PrePost,LCMFreq,AprioriClose,DCI_Closed,Charm_bitset,LCM,FPClose,NAFCP,NEclatClosed,FPMax,Charm_MFI,DefMe,Pascal,Zart,AprioriRare,Two-Phase,FHM, EFIM, D2HUP,FHM+,CHUI-MinerMax,AprioriInverse,AprioriInverse_TID
  min_support: 0.5%
  max_support: 1% # for AprioriInverse
  min_support_count: 1 # for algos that expect integer support count
  max_pattern_length: 6
  min_pattern_length: 1
  show_transaction_ids: False #for algorithms that return TIDs
  high_utility_itemsets: False # For high utility mining algos
  min_utility: 1 # for high utility mining algos
  sort_input_items: #  some algos require sorted items
    enable: True
    ascending: True
  replace_zero: # some algos can only handle positive integers
    enable: True
    replace_zero_with: 1000
  jar_file: ./lib/spmfe.jar

anomalyscoring:
  which: matrixprofile
  matrixprofile:
    subsequence_length: 100 # to calculate z-normalized Euclidean distance
    auto_subsequence_length: False # if True, the subsequence_length will not be used
    save_scores: False # to save time for tests
    cpu_cores: 8 # number of cpu cores to use
    sample_pct: 1 # sample percentage for anytime, use "1" for exact
  iForest:
    num_trees: 100
data:
  dataset_title: pvsystem
  dataset_file_name: pvsystem_data.csv
  dataset_gt_file_name: pvsystem_GT.csv
  ground_truth_type: range # or "point" for each anomaly
  data_gt_single_file: False
  dataset_path: ./data/raw/pvsystem/
  spmf_output_path: ./data/output/spmf/
  final_output_path: ./data/output/final/
  processed_data_path: ./data/processed/
  transactions_path: ./data/processed/saved_transactions/
  scores_path: ./data/processed/saved_scores/
  transaction_db_path: ./data/processed/transaction_databases/
  label_pad_size: 50
logging:
  console_log_level: INFO
  log_dir: ./logs/
  log_file_prefix: dev
plot:
  output_path: ./plots/
  subplot_size: 50
  show_dataset: True
  show_matrixprofile: True
  show_single_dim_mp: True
  single_dim: 20
  show_kdp: False
  show_detected_anomalies_vs_gt: True
  show_final_output: False
